[workspace]
members = [
    "./",
    "crates/dnd-m8-core",
    "crates/dnd-m8-ruleset",
    "crates/rulesets/dnd-m8-srd5-2-1"
]

[workspace.package]
version                         = "0.0.1"
description                     = "An interactive, cross-platform D&D character sheet"
authors                         = ["mrbya <v.toth.svk2@gmail.com>"]
edition                         = "2021"
license                         = "MIT"

[package]
name                            = "dnd-m8"
version.workspace               = true
description.workspace           = true
authors.workspace               = true
edition.workspace               = true

[workspace.dependencies]
# Build deps
tauri-build                     = { version = "2", features = [] }
# Workspace crates
dnd-m8-core                     = { path = "crates/dnd-m8-core" }
dnd-m8-ruleset                  = { path = "crates/dnd-m8-ruleset" }
# Rulesets
dnd-m8-srd5-2-1                = { path = "crates/rulesets/dnd-m8-srd5-2-1" }
# Runtime deps
tauri                           = { version = "2", features = [] }
tauri-plugin-opener             = { version = "2" }
serde                           = { version = "1", features = ["derive"] }
serde_json                      = { version = "1" }
semver                          = { version = "1" }
thiserror                       = { version = "2" }
uuid                            = { version = "1", features = ["v4"] }
# Dev deps
pretty_assertions               = { version = "1" }

[lib]
name                            = "dnd_m8_lib"
crate-type                      = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build.workspace           = true

[dependencies]
tauri.workspace                 = true
tauri-plugin-opener.workspace   = true
serde.workspace                 = true
serde_json.workspace            = true

[dev-dependencies]
pretty_assertions.workspace     = true

[package.metadata.cargo-udeps.ignore]
normal = [
    "dnd-m8-core",
    "dnd-m8-ruleset",
    "dnd-m8-srd-5-2-1",
]
development = ["pretty_assertions"]

# Read the optimization guideline for more details: https://tauri.app/concept/size/#cargo-configuration
[profile.release]
codegen-units = 1
lto = true
opt-level = 3
panic = "abort"
strip = true
